### ISSUE TITLE
RSpec + Github Actions

### ISSUE THREAD

**Issue by igorkasyanchuk** [meilisearch/meilisearch-rails#236]
**Description**

Can't make CI work with Meilisearch.

**Expected behavior**

My specs passed on CI :)

**Current behavior**

<img width="901" alt="image" src="https://user-images.githubusercontent.com/11101/216770003-f3927108-312e-406a-b5f4-bc9768d749e3.png">

**Screenshots or Logs**

See above

**Environment (please complete the following information):**
```yaml
name: CI
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      GITHUNT_BASE_URL: https://githunt.info
      GITHUNT_HTTP_BASIC_USER: 1
      GITHUNT_HTTP_BASIC_PASSWORD: 1
      RAILS_ENV: test
      MEILISEARCH_HOST: http://localhost:7700
      MEILISEARCH_URL: http://localhost:7700
      MEILISEARCH_API_KEY: masterKey
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
          cache-version: 1
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev libvips
      - name: Install some libs
        run: |
          sudo apt-get -yqq install libvips
      - name: Build App
        run: |
          bin/rails db:create db:migrate
      - name: StandardRB Setup
        uses: andrewmcodes/standardrb-action@v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: StandardRB Action Lint
        run: bundle exec standardrb
      - name: MeiliSearch (latest) setup with Docker
        run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --master-key=masterKey --no-analytics=true
        env:
          MEILISEARCH_HOST: http://localhost:7700
          MEILISEARCH_URL: http://localhost:7700
          MEILISEARCH_API_KEY: masterKey
      - name: Run rspec
        run: bundle exec rspec
```
